# -*- coding: utf-8 -*-
"""
EVODjango enumerations
===============================================

.. module:: evodjango.enums
    :platform: Django
    :synopsis: EVODjango enumerations module
.. moduleauthor:: (C) 2012 Oliver Gutiérrez
"""

# Django imports
from django.utils.translation import ugettext_lazy as _

#===============================================================================
# Genders
#===============================================================================
GENDERS=(
    ('m',_('Male')),
    ('f',_('Female')),
    ('o',_('Other')),
)

#===============================================================================
# Honorific titles
#===============================================================================
HONORIFIC_TITLES=(
    ('MR',_('Mr.')),
    ('MRS',_('Mrs.')),
    ('MS',_('Ms.')),
)

#===============================================================================
# World countries
#===============================================================================
COUNTRIES=(
    ('af',_('Afghanistan')),
    ('ax',_('Aland Islands')),
    ('al',_('Albania')),
    ('dz',_('Algeria')),
    ('as',_('American Samoa')),
    ('ad',_('Andorra')),
    ('ao',_('Angola')),
    ('ai',_('Anguilla')),
    ('aq',_('Antarctica')),
    ('ag',_('Antigua and Barbuda')),
    ('ar',_('Argentina')),
    ('am',_('Armenia')),
    ('aw',_('Aruba')),
    ('au',_('Australia')),
    ('at',_('Austria')),
    ('az',_('Azerbaijan')),
    ('bs',_('Bahamas')),
    ('bh',_('Bahrain')),
    ('bd',_('Bangladesh')),
    ('bb',_('Barbados')),
    ('by',_('Belarus')),
    ('be',_('Belgium')),
    ('bz',_('Belize')),
    ('bj',_('Benin')),
    ('bm',_('Bermuda')),
    ('bt',_('Bhutan')),
    ('bo',_('Bolivia')),
    ('ba',_('Bosnia and Herzegovina')),
    ('bw',_('Botswana')),
    ('bv',_('Bouvet Island')),
    ('br',_('Brazil')),
    ('io',_('British indian ocean territory')),
    ('bn',_('Brunei Darussalam')),
    ('bg',_('Bulgaria')),
    ('bf',_('Burkina Faso')),
    ('bi',_('Burundi')),
    ('kh',_('Cambodia')),
    ('cm',_('Cameroon')),
    ('ca',_('Canada')),
    ('cv',_('Cape Verde')),
    ('ky',_('Cayman Islands')),
    ('cf',_('Central African Republic')),
    ('td',_('Chad')),
    ('cl',_('Chile')),
    ('cn',_('China')),
    ('cx',_('Christmas Island')),
    ('cc',_('Cocos (Keeling) Islands')),
    ('co',_('Colombia')),
    ('km',_('Comoros')),
    ('cg',_('Congo')),
    ('cd',_('Congo, the Democratic Republic of the')),
    ('ck',_('Cook islands')),
    ('cr',_('Costa rica')),
    ('ci',_('Cote d\'ivoire')),
    ('hr',_('Croatia')),
    ('cu',_('Cuba')),
    ('cy',_('Cyprus')),
    ('cz',_('Czech republic')),
    ('dk',_('Denmark')),
    ('dj',_('Djibouti')),
    ('dm',_('Dominica')),
    ('do',_('Dominican Republic')),
    ('ec',_('Ecuador')),
    ('eg',_('Egypt')),
    ('sv',_('El salvador')),
    ('gq',_('Equatorial Guinea')),
    ('er',_('Eritrea')),
    ('ee',_('Estonia')),
    ('et',_('Ethiopia')),
    ('fk',_('Falkland Islands (Malvinas)')),
    ('fo',_('Faroe islands')),
    ('fj',_('Fiji')),
    ('fi',_('Finland')),
    ('fr',_('France')),
    ('gf',_('French Guiana')),
    ('pf',_('French Polynesia')),
    ('tf',_('French southern territories')),
    ('ga',_('Gabon')),
    ('gm',_('Gambia')),
    ('ge',_('Georgia')),
    ('de',_('Germany')),
    ('gh',_('Ghana')),
    ('gi',_('Gibraltar')),
    ('gr',_('Greece')),
    ('gl',_('Greenland')),
    ('gd',_('Grenada')),
    ('gp',_('Guadeloupe')),
    ('gu',_('Guam')),
    ('gt',_('Guatemala')),
    ('gn',_('Guinea')),
    ('gw',_('Guinea-bissau')),
    ('gy',_('Guyana')),
    ('ht',_('Haiti')),
    ('hm',_('Heard Island and McDonald Islands')),
    ('va',_('Holy see (Vatican City State)')),
    ('hn',_('Honduras')),
    ('hk',_('Hong kong')),
    ('hu',_('Hungary')),
    ('is',_('Iceland')),
    ('in',_('India')),
    ('id',_('Indonesia')),
    ('ir',_('Iran, Islamic Republic of')),
    ('iq',_('Iraq')),
    ('ie',_('Ireland')),
    ('il',_('Israel')),
    ('it',_('Italy')),
    ('jm',_('Jamaica')),
    ('jp',_('Japan')),
    ('jo',_('Jordan')),
    ('kz',_('Kazakhstan')),
    ('ke',_('Kenya')),
    ('ki',_('Kiribati')),
    ('kp',_('Korea, Democratic People\'s Republic of')),
    ('kr',_('Korea, Republic of')),
    ('kw',_('Kuwait')),
    ('kg',_('Kyrgyzstan')),
    ('la',_('Lao people\'s Democratic Republic')),
    ('lv',_('Latvia')),
    ('lb',_('Lebanon')),
    ('ls',_('Lesotho')),
    ('lr',_('Liberia')),
    ('ly',_('Libyan Arab Jamahiriya')),
    ('li',_('Liechtenstein')),
    ('lt',_('Lithuania')),
    ('lu',_('Luxembourg')),
    ('mo',_('Macao')),
    ('mk',_('Macedonia, the former Yugoslav Republic of')),
    ('mg',_('Madagascar')),
    ('mw',_('Malawi')),
    ('my',_('Malaysia')),
    ('mv',_('Maldives')),
    ('ml',_('Mali')),
    ('mt',_('Malta')),
    ('mh',_('Marshall Islands')),
    ('mq',_('Martinique')),
    ('mr',_('Mauritania')),
    ('mu',_('Mauritius')),
    ('yt',_('Mayotte')),
    ('mx',_('Mexico')),
    ('fm',_('Micronesia, Federated States of')),
    ('md',_('Moldova, Republic of')),
    ('mc',_('Monaco')),
    ('mn',_('Mongolia')),
    ('ms',_('Montserrat')),
    ('ma',_('Morocco')),
    ('mz',_('Mozambique')),
    ('mm',_('Myanmar')),
    ('na',_('Namibia')),
    ('nr',_('Nauru')),
    ('np',_('Nepal')),
    ('nl',_('Netherlands')),
    ('an',_('Netherlands Antilles')),
    ('nc',_('New Caledonia')),
    ('nz',_('New Zealand')),
    ('ni',_('Nicaragua')),
    ('ne',_('Niger')),
    ('ng',_('Nigeria')),
    ('nu',_('Niue')),
    ('nf',_('Norfolk Island')),
    ('mp',_('Northern Mariana Islands')),
    ('no',_('Norway')),
    ('om',_('Oman')),
    ('pk',_('Pakistan')),
    ('pw',_('Palau')),
    ('ps',_('Palestinian yerritory, occupied')),
    ('pa',_('Panama')),
    ('pg',_('Papua New Guinea')),
    ('py',_('Paraguay')),
    ('pe',_('Peru')),
    ('ph',_('Philippines')),
    ('pn',_('Pitcairn')),
    ('pl',_('Poland')),
    ('pt',_('Portugal')),
    ('pr',_('Puerto Rico')),
    ('qa',_('Qatar')),
    ('re',_('Reunion')),
    ('ro',_('Romania')),
    ('ru',_('Russian Federation')),
    ('rw',_('Rwanda')),
    ('sh',_('Saint Helena')),
    ('kn',_('Saint Kitts and Nevis')),
    ('lc',_('Saint Lucia')),
    ('pm',_('Saint Pierre and Miquelon')),
    ('vc',_('Saint Vincent and the Grenadines')),
    ('ws',_('Samoa')),
    ('sm',_('San marino')),
    ('st',_('Sao Tome and Principe')),
    ('sa',_('Saudi Arabia')),
    ('sn',_('Senegal')),
    ('cs',_('Serbia and Montenegro')),
    ('sc',_('Seychelles')),
    ('sl',_('Sierra Leone')),
    ('sg',_('Singapore')),
    ('sk',_('Slovakia')),
    ('si',_('Slovenia')),
    ('sb',_('Solomon Islands')),
    ('so',_('Somalia')),
    ('za',_('South Africa')),
    ('gs',_('South Georgia and the south Sandwich Islands')),
    ('es',_('Spain')),
    ('lk',_('Sri Lanka')),
    ('sd',_('Sudan')),
    ('sr',_('Suriname')),
    ('sj',_('Svalbard and Jan Mayen')),
    ('sz',_('Swaziland')),
    ('se',_('Sweden')),
    ('ch',_('Switzerland')),
    ('sy',_('Syrian Arab Republic')),
    ('tw',_('Taiwan, province of China')),
    ('tj',_('Tajikistan')),
    ('tz',_('Tanzania, United Republic of')),
    ('th',_('Thailand')),
    ('tl',_('Timor-Leste')),
    ('tg',_('Togo')),
    ('tk',_('Tokelau')),
    ('to',_('Tonga')),
    ('tt',_('Trinidad and Tobago')),
    ('tn',_('Tunisia')),
    ('tr',_('Turkey')),
    ('tm',_('Turkmenistan')),
    ('tc',_('Turks and Caicos Islands')),
    ('tv',_('Tuvalu')),
    ('ug',_('Uganda')),
    ('ua',_('Ukraine')),
    ('ae',_('United Arab Emirates')),
    ('gb',_('United Kingdom')),
    ('us',_('United States')),
    ('um',_('United States minor outlying islands')),
    ('uy',_('Uruguay')),
    ('uz',_('Uzbekistan')),
    ('vu',_('Vanuatu')),
    ('ve',_('Venezuela')),
    ('vn',_('Viet nam')),
    ('vg',_('Virgin Islands, british')),
    ('vi',_('Virgin Islands, u.s.')),
    ('wf',_('Wallis and Futuna')),
    ('eh',_('Western Sahara')),
    ('ye',_('Yemen')),
    ('zm',_('Zambia')),
    ('zw',_('Zimbabwe')),
)

#===============================================================================
# Currency codes
#===============================================================================
CURRENCY_CODES=(
    ('AED',_('United Arab Emirates, Dirhams')),
    ('AFN',_('Afghanistan, Afghanis')),
    ('ALL',_('Albania, Leke')),
    ('AMD',_('Armenia, Drams')),
    ('ANG',_('Netherlands Antilles, Guilders (also called Florins)')),
    ('AOA',_('Angola, Kwanza')),
    ('ARS',_('Argentina, Pesos')),
    ('AUD',_('Australia, Dollars')),
    ('AWG',_('Aruba, Guilders (also called Florins)')),
    ('AZN',_('Azerbaijan, New Manats')),
    ('BAM',_('Bosnia and Herzegovina, Convertible Marka')),
    ('BBD',_('Barbados, Dollars')),
    ('BDT',_('Bangladesh, Taka')),
    ('BGN',_('Bulgaria, Leva')),
    ('BHD',_('Bahrain, Dinars')),
    ('BIF',_('Burundi, Francs')),
    ('BMD',_('Bermuda, Dollars')),
    ('BND',_('Brunei Darussalam, Dollars')),
    ('BOB',_('Bolivia, Bolivianos')),
    ('BRL',_('Brazil, Brazil Real')),
    ('BSD',_('Bahamas, Dollars')),
    ('BTN',_('Bhutan, Ngultrum')),
    ('BWP',_('Botswana, Pulas')),
    ('BYR',_('Belarus, Rubles')),
    ('BZD',_('Belize, Dollars')),
    ('CAD',_('Canada, Dollars')),
    ('CDF',_('Congo/Kinshasa, Congolese Francs')),
    ('CHF',_('Switzerland, Francs')),
    ('CLP',_('Chile, Pesos')),
    ('CNY',_('China, Yuan Renminbi')),
    ('COP',_('Colombia, Pesos')),
    ('CRC',_('Costa Rica, Colones')),
    ('CUP',_('Cuba, Pesos')),
    ('CVE',_('Cape Verde, Escudos')),
    ('CZK',_('Czech Republic, Koruny')),
    ('DJF',_('Djibouti, Francs')),
    ('DKK',_('Denmark, Kroner')),
    ('DOP',_('Dominican Republic, Pesos')),
    ('DZD',_('Algeria, Algeria Dinars')),
    ('EGP',_('Egypt, Pounds')),
    ('ERN',_('Eritrea, Nakfa')),
    ('ETB',_('Ethiopia, Birr')),
    ('EUR',_('Euro Member Countries, Euro')),
    ('FJD',_('Fiji, Dollars')),
    ('FKP',_('Falkland Islands (Malvinas)), Pounds')),
    ('GBP',_('United Kingdom, Pounds')),
    ('GEL',_('Georgia, Lari')),
    ('GGP',_('Guernsey, Pounds')),
    ('GHS',_('Ghana, Cedis')),
    ('GIP',_('Gibraltar, Pounds')),
    ('GMD',_('Gambia, Dalasi')),
    ('GNF',_('Guinea, Francs')),
    ('GTQ',_('Guatemala, Quetzales')),
    ('GYD',_('Guyana, Dollars')),
    ('HKD',_('Hong Kong, Dollars')),
    ('HNL',_('Honduras, Lempiras')),
    ('HRK',_('Croatia, Kuna')),
    ('HTG',_('Haiti, Gourdes')),
    ('HUF',_('Hungary, Forint')),
    ('IDR',_('Indonesia, Rupiahs')),
    ('ILS',_('Israel, New Shekels')),
    ('IMP',_('Isle of Man, Pounds')),
    ('INR',_('India, Rupees')),
    ('IQD',_('Iraq, Dinars')),
    ('IRR',_('Iran, Rials')),
    ('ISK',_('Iceland, Kronur')),
    ('JEP',_('Jersey, Pounds')),
    ('JMD',_('Jamaica, Dollars')),
    ('JOD',_('Jordan, Dinars')),
    ('JPY',_('Japan, Yen')),
    ('KES',_('Kenya, Shillings')),
    ('KGS',_('Kyrgyzstan, Soms')),
    ('KHR',_('Cambodia, Riels')),
    ('KMF',_('Comoros, Francs')),
    ('KPW',_('Korea (North), Won')),
    ('KRW',_('Korea (South)), Won')),
    ('KWD',_('Kuwait, Dinars')),
    ('KYD',_('Cayman Islands, Dollars')),
    ('KZT',_('Kazakhstan, Tenge')),
    ('LAK',_('Laos, Kips')),
    ('LBP',_('Lebanon, Pounds')),
    ('LKR',_('Sri Lanka, Rupees')),
    ('LRD',_('Liberia, Dollars')),
    ('LSL',_('Lesotho, Maloti')),
    ('LTL',_('Lithuania, Litai')),
    ('LVL',_('Latvia, Lati')),
    ('LYD',_('Libya, Dinars')),
    ('MAD',_('Morocco, Dirhams')),
    ('MDL',_('Moldova, Lei')),
    ('MGA',_('Madagascar, Ariary')),
    ('MKD',_('Macedonia, Denars')),
    ('MMK',_('Myanmar (Burma)), Kyats')),
    ('MNT',_('Mongolia, Tugriks')),
    ('MOP',_('Macau, Patacas')),
    ('MRO',_('Mauritania, Ouguiyas')),
    ('MUR',_('Mauritius, Rupees')),
    ('MVR',_('Maldives (Maldive Islands)), Rufiyaa')),
    ('MWK',_('Malawi, Kwachas')),
    ('MXN',_('Mexico, Pesos')),
    ('MYR',_('Malaysia, Ringgits')),
    ('MZN',_('Mozambique, Meticais')),
    ('NAD',_('Namibia, Dollars')),
    ('NGN',_('Nigeria, Nairas')),
    ('NIO',_('Nicaragua, Cordobas')),
    ('NOK',_('Norway, Krone')),
    ('NPR',_('Nepal, Nepal Rupees')),
    ('NZD',_('New Zealand, Dollars')),
    ('OMR',_('Oman, Rials')),
    ('PAB',_('Panama, Balboa')),
    ('PEN',_('Peru, Nuevos Soles')),
    ('PGK',_('Papua New Guinea, Kina')),
    ('PHP',_('Philippines, Pesos')),
    ('PKR',_('Pakistan, Rupees')),
    ('PLN',_('Poland, Zlotych')),
    ('PYG',_('Paraguay, Guarani')),
    ('QAR',_('Qatar, Rials')),
    ('RON',_('Romania, New Lei')),
    ('RSD',_('Serbia, Dinars')),
    ('RUB',_('Russia, Rubles')),
    ('RWF',_('Rwanda, Rwanda Francs')),
    ('SAR',_('Saudi Arabia, Riyals')),
    ('SBD',_('Solomon Islands, Dollars')),
    ('SCR',_('Seychelles, Rupees')),
    ('SDG',_('Sudan, Pounds')),
    ('SEK',_('Sweden, Kronor')),
    ('SGD',_('Singapore, Dollars')),
    ('SHP',_('Saint Helena, Pounds')),
    ('SLL',_('Sierra Leone, Leones')),
    ('SOS',_('Somalia, Shillings')),
    ('SPL',_('Seborga, Luigini')),
    ('SRD',_('Suriname, Dollars')),
    ('STD',_('Sao Tome and Principe, Dobras')),
    ('SVC',_('El Salvador, Colones')),
    ('SYP',_('Syria, Pounds')),
    ('SZL',_('Swaziland, Emalangeni')),
    ('THB',_('Thailand, Baht')),
    ('TJS',_('Tajikistan, Somoni')),
    ('TMM',_('Turkmenistan, Manats')),
    ('TND',_('Tunisia, Dinars')),
    ('TOP',_('Tonga, Pa\'anga')),
    ('TRY',_('Turkey, New Lira')),
    ('TTD',_('Trinidad and Tobago, Dollars')),
    ('TVD',_('Tuvalu, Tuvalu Dollars')),
    ('TWD',_('Taiwan, New Dollars')),
    ('TZS',_('Tanzania, Shillings')),
    ('UAH',_('Ukraine, Hryvnia')),
    ('UGX',_('Uganda, Shillings')),
    ('USD',_('United States of America, Dollars')),
    ('UYU',_('Uruguay, Pesos')),
    ('UZS',_('Uzbekistan, Sums')),
    ('VEF',_('Venezuela, Bolivares Fuertes')),
    ('VND',_('Viet Nam, Dong')),
    ('VUV',_('Vanuatu, Vatu')),
    ('WST',_('Samoa, Tala')),
    ('XAF',_('Communaute Financiere Africaine BEAC, Francs')),
    ('XAG',_('Silver, Ounces')),
    ('XAU',_('Gold, Ounces')),
    ('XCD',_('East Caribbean Dollars')),
    ('XDR',_('International Monetary Fund (IMF) Special Drawing Rights')),
    ('XOF',_('Communaute Financiere Africaine BCEAO, Francs')),
    ('XPD',_('Palladium Ounces')),
    ('XPF',_('Comptoirs Francais du Pacifique Francs')),
    ('XPT',_('Platinum, Ounces')),
    ('YER',_('Yemen, Rials')),
    ('ZAR',_('South Africa, Rand')),
    ('ZMK',_('Zambia, Kwacha')),
    ('ZWD',_('Zimbabwe, Zimbabwe Dollars')),
)

#===============================================================================
# Barcode standards
#===============================================================================
BARCODE_TYPES=(
    ('C39','Code 39'),
    ('C128','Code 128B'),
    ('C128C','Code 128C'),
    ('C128R','Code 128R'),
    ('EAN','EAN'),
    ('ISBN','ISBN'),
    ('UPC','UPC'),
    ('CI25','Code I25'),
    ('CBR','CBR'),
    ('MSI','MSI'),
    ('PLS','PLS'),
    ('C93','Code 93'),
)

#===============================================================================
# HTTP protocol request methods
#===============================================================================
HTTP_REQUEST_METHODS=(
    ('GET','Get'),
    ('POST','Post'),
    ('PUT','Put'),
    ('DELETE','Delete'),
    ('CONNECT','Connect'),
    ('HEAD','Head'),
    ('TRACE','Trace'),
)

#===============================================================================
# TLDs list as specified in http://data.iana.org/TLD/tlds-alpha-by-domain.txt
# Version 2011121100, Last Updated Sun Dec 11 15:07:01 2011 UTC
#===============================================================================
TLD_LIST=(
    'AC','AD','AE','AERO','AF','AG','AI','AL','AM','AN','AO','AQ','AR','ARPA','AS','ASIA','AT','AU',
    'AW','AX','AZ','BA','BB','BD','BE','BF','BG','BH','BI','BIZ','BJ','BM','BN','BO','BR','BS','BT',
    'BV','BW','BY','BZ','CA','CAT','CC','CD','CF','CG','CH','CI','CK','CL','CM','CN','CO','COM',
    'COOP','CR','CU','CV','CW','CX','CY','CZ','DE','DJ','DK','DM','DO','DZ','EC','EDU','EE','EG',
    'ER','ES','ET','EU','FI','FJ','FK','FM','FO','FR','GA','GB','GD','GE','GF','GG','GH','GI','GL',
    'GM','GN','GOV','GP','GQ','GR','GS','GT','GU','GW','GY','HK','HM','HN','HR','HT','HU','ID','IE',
    'IL','IM','IN','INFO','INT','IO','IQ','IR','IS','IT','JE','JM','JO','JOBS','JP','KE','KG','KH',
    'KI','KM','KN','KP','KR','KW','KY','KZ','LA','LB','LC','LI','LK','LR','LS','LT','LU','LV','LY',
    'MA','MC','MD','ME','MG','MH','MIL','MK','ML','MM','MN','MO','MOBI','MP','MQ','MR','MS','MT',
    'MU','MUSEUM','MV','MW','MX','MY','MZ','NA','NAME','NC','NE','NET','NF','NG','NI','NL','NO',
    'NP','NR','NU','NZ','OM','ORG','PA','PE','PF','PG','PH','PK','PL','PM','PN','PR','PRO','PS',
    'PT','PW','PY','QA','RE','RO','RS','RU','RW','SA','SB','SC','SD','SE','SG','SH','SI','SJ','SK',
    'SL','SM','SN','SO','SR','ST','SU','SV','SX','SY','SZ','TC','TD','TEL','TF','TG','TH','TJ',
    'TK','TL','TM','TN','TO','TP','TR','TRAVEL','TT','TV','TW','TZ','UA','UG','UK','US','UY','UZ',
    'VA','VC','VE','VG','VI','VN','VU','WF','WS','XN--0ZWM56D','XN--11B5BS3A9AJ6G','XN--3E0B707E',
    'XN--45BRJ9C','XN--80AKHBYKNJ4F','XN--90A3AC','XN--9T4B11YI5A','XN--CLCHC0EA0B2G2A9GCD',
    'XN--DEBA0AD','XN--FIQS8S','XN--FIQZ9S','XN--FPCRJ9C3D','XN--FZC2C9E2C','XN--G6W251D',
    'XN--GECRJ9C','XN--H2BRJ9C','XN--HGBK6AJ7F53BBA','XN--HLCJ6AYA9ESC7A','XN--J6W193G',
    'XN--JXALPDLP','XN--KGBECHTV','XN--KPRW13D','XN--KPRY57D','XN--LGBBAT1AD8J','XN--MGBAAM7A8H',
    'XN--MGBAYH7GPA','XN--MGBBH1A71E','XN--MGBC0A9AZCG','XN--MGBERP4A5D4AR','XN--O3CW4H',
    'XN--OGBPF8FL','XN--P1AI','XN--PGBS0DH','XN--S9BRJ9C','XN--WGBH1C','XN--WGBL6A',
    'XN--XKC2AL3HYE2A','XN--XKC2DL3A5EE0H','XN--YFRO4I67O','XN--YGBI2AMMX','XN--ZCKZAH','XXX','YE',
    'YT','ZA','ZM','ZW',
)
